# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Brightspots' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Brightspots
  pod 'FontAwesome.swift'
  pod 'AloeStackView'
  pod 'PureLayout'
  pod 'ScrollableGraphView'
  pod 'MaterialComponents/Cards'
  pod 'MaterialComponents/schemes/Color'
  pod 'MaterialComponents/Cards+ColorThemer'
  pod 'Auth0', '~> 1.13'
  pod 'paper-onboarding'


  target 'BrightspotsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BrightspotsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
